# Generated by Django 5.0.6 on 2024-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='ratting',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
